---

  #- debug: msg=" {{ groups['nodes'] | join(',') }} "

  - name: Install GlusterFs repo
    yum:
      name: centos-release-gluster
      state: latest

  - name: Install GlusterFs Server
    yum:
      name: glusterfs-server
      state: latest

  - name: Enable/Start glusterd service
    service:
      name: glusterd
      enabled: yes
      state: started

  - name: Wait for glusterfsd to start
    wait_for:
      host: localhost
      port: 24007
      delay: 10
      state: started

  - set_fact:
      peer_list: |
        {% set comma = joiner(",") %}
        {% for item in groups['nodes'] -%}
            {{ comma() }}{{ hostvars[item].ansible_default_ipv4.address }}
        {%- endfor %}
    run_once: true

  - name: create gluster volume
    gluster_volume:
      state: present
      name: gluster_vol-1
      bricks: /gluster_vol-1
      #rebalance: yes
      cluster: "{{ peer_list | replace('\n', '') }}"
      replicas: "2"
      force: true
    run_once: true
