apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 46.101.192.50
    ports:
      - port: 1
  - addresses:
      - ip: 46.101.129.172
    ports:
      - port: 1
