apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 138.68.81.157
    ports:
      - port: 1
  - addresses:
      - ip: 138.68.104.97
    ports:
      - port: 1
