apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 138.68.77.226
    ports:
      - port: 1
  - addresses:
      - ip: 138.68.77.250
    ports:
      - port: 1
