apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 138.68.71.147
    ports:
      - port: 1
  - addresses:
      - ip: 138.68.71.177
    ports:
      - port: 1
