apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 46.101.245.129
    ports:
      - port: 1
  - addresses:
      - ip: 46.101.181.147
    ports:
      - port: 1
