apiVersion: v1
kind: Service
metadata:
  name: open-data-lv-php
  labels:
    app: open-data-lv
spec:
  ports:
    - port: 80
  selector:
    app: open-data-lv
    tier: php
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: open-data-lv-php
  labels:
    app: open-data-lv
spec:
  template:
    metadata:
      labels:
        app: open-data-lv
        tier: php
    spec:
      containers:
      - image: php/7.0-cli
        name: php
