[master]
master.example.com ansible_host=46.101.255.226

[nodes]
node-1.example.com ansible_host=46.101.192.50
node-2.example.com ansible_host=46.101.129.172

[all-k8s-nodes:children]
master
nodes

[digitalocean]
localhost ansible_connection=local
