[master]
master.example.com ansible_host=138.68.81.172

[nodes]
node-1.example.com ansible_host=46.101.117.32
#node-2.example.com ansible_host=138.68.81.192

[all-k8s-nodes:children]
master
nodes

[digitalocean]
localhost ansible_connection=local
