[master]
master.example.com ansible_host=46.101.103.194

[nodes:children]
vultr_nodes
do_nodes
scaleway_nodes

[nodes_pub_access_eth:children]
vultr_nodes
do_nodes

[vultr_nodes]
#node-5.example.com ansible_host=108.61.103.92
#node-7.example.com ansible_host=45.76.136.108

[do_nodes]
#node-1.example.com ansible_host=165.227.134.78

[scaleway_nodes]
node-11.example.com ansible_host=212.47.244.3
node-12.example.com ansible_host=51.15.135.115
node-13.example.com ansible_host=51.15.37.65
node-14.example.com ansible_host=51.15.61.73
node-15.example.com ansible_host=212.47.251.14

[all-k8s-nodes:children]
master
nodes

[digitalocean]
localhost ansible_connection=local
