---

  - name: Install flannel
    yum:
      name: flannel
      state: latest

  - name: Add flannel conf
    template:
      src: flannel.j2
      dest: /etc/sysconfig/flanneld
    notify:
      - restart flannel

  - name: Check flannel for network cfg.
    shell: "etcdctl ls atomic.io/network/config"
    changed_when: False
    register: out
    ignore_errors: yes

  - name: Create k8 network cfg. file
    template:
      src: flannel-config.json.j2
      dest: /root/flannel-config.json
    changed_when: False
    when:  "'Key not found' in out.stderr"

  - name: Store flannel network cfg. in etcd
    shell: "etcdctl set atomic.io/network/config < /root/flannel-config.json"
    when:  "'Key not found' in out.stderr"

  - name: Enable flanneld service
    service:
      name: flanneld
      enabled: yes
      state: started
    notify:
      - restart docker

  - name: Add docker drop in cfg.
    copy:
      src: flannel.conf
      dest: /usr/lib/systemd/system/docker.service.d/flannel.conf
      mode: 0644
    notify:
      - restart docker
