---

  - name: Install flannel
    yum:
      name: flannel
      state: latest

  - name: Add flannel conf
    template:
      src: flannel.j2
      dest: /etc/sysconfig/flanneld

  - name: Check flannel for network cfg.
    shell: "etcdctl ls atomic.io/network/config"
    changed_when: False
    register: out
    ignore_errors: yes

  - name: Create k8 network cfg. file
    template:
      src: flannel-config.json.j2
      dest: /root/flannel-config.json
    changed_when: False
    when:  "'Key not found' in out.stderr"

  - name: Store flannel network cfg. in etcd
    shell: "etcdctl set atomic.io/network/config < /root/flannel-config.json"
    when:  "'Key not found' in out.stderr"

  - name: Check docker existence
    command: docker version
    register: has_docker
    changed_when: false
    failed_when: false

  - name: stop docker (to delete docker0 intf.)
    service: name=docker state=stopped
    when: '"docker0" in ansible_interfaces'

  - name: delete docker0 intf.
    command: ip link delete docker0
    when: '"docker0" in ansible_interfaces'

  - name: docker start service
    service:
      name: docker
      state: started
    when: has_docker.rc|int != 2

  - name: Enable flanneld service
    service:
      name: flanneld
      enabled: yes
      state: started
