apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
  namespace: crawler
  labels:
    component: busybox
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
