apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: kube-system
spec:
  containers:
  - image: centos
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: centos
  restartPolicy: Always
  nodeSelector:
    node: master
