---

  - name: Move kubelet binarys to sys path.
    command: cp -v /root/kubernetes/server/bin/kubelet /usr/bin/kubelet creates=/usr/bin/kubelet

  - name: Clone github repo kubernetes/contrib
    git:
      repo: https://github.com/kubernetes/contrib.git
      dest: /root/contrib

  - name: Copy kubelet.service file
    command: cp -v /root/contrib/init/systemd/kubelet.service /usr/lib/systemd/system/kubelet.service creates=/usr/lib/systemd/system/kubelet.service

  - name: Create the /var/lib/kubelet working directory
    file:
      path: /var/lib/kubelet
      state: directory

  - include: kubelet-cfg.yml

  - name: Enable/Start kubelet service
    service:
      name: kubelet
      enabled: yes
      state: started
