---

  - name: Generate root sshkey on master
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_type: rsa
    register: rootkeys
    delegate_to: "{{ groups['master'][0] }}"

  - debug: var=rootkeys.ssh_public_key

  - name: Place pubkeys in authorized_keys on nodes 
    authorized_key:
      key: "{{ rootkeys.ssh_public_key }}"
      state: present
      user: root
