---

  - name: Create a skydns-rc / skydns-svc tmeplate
    template:
      src: "{{ item}}.yaml.j2"
      dest: "/root/{{ item }}.yaml"
    with_items:
      - skydns-rc
      - skydns-svc

  - name: Create a rc and service
    command: "kubectl create -f /root/{{ item }}.yaml"
    register: out
    with_items:
      - skydns-rc
      - skydns-svc
    ignore_errors: yes
