#cloud-config

coreos:
  update:
    reboot-strategy: off
  etcd2:
    discovery: "https://discovery.etcd.io/7859689e8ab7f442a0a986563c05539f"
    advertise-client-urls: "http://$public_ipv4:2379,http://$public_ipv4:4001"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
  flannel:
    interface: $public_ipv4
    etcd_endpoints: http://$public_ipv4:2379
  fleet:
    public-ip: $public_ipv4
  units:
    - name: fleet.service
      command: start
    - name: etcd2.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
      command: start
