---

  - name: Create /etc/kubernetes dir
    file:
      path: /etc/kubernetes/manifests
      state: directory

  - name: Create api/controller/scheduler pods
    template:
      src: "{{ item }}.j2"
      dest: "/etc/kubernetes/manifests/{{ item }}"
    with_items:
      - apiserver.pod.json
      - controller-manager.pod.json
      - scheduler.pod.json
    notify:
      - restart kubelet 
